### ISSUE TITLE
### It's basically what the friend had already said above, but I'll give details on how to solve it.

### ISSUE THREAD

**Issue by ThomasJPF** [grafana/grafana-zabbix#1677]
### It's basically what the friend had already said above, but I'll give details on how to solve it.

**Check the version of lld by running the command:**

> `ldd --version`

**My case I'm using debian, update lld to the latest version, acceptable:**

> 
> ```
> echo "deb http://ftp.debian.org/debian sid main" >> /etc/apt/sources.list
> apt-get update
> apt-get -t sid install libc6 libc6-dev libc6-dbg
> ```
**This procedure must be done inside the plugin folder**

**You must run the GPX that corresponds to your OS:**

> `./gpx_zabbix-plugin_linux_amd64 `

```
> root@frontzabbix:/var/lib/grafana/plugins/alexanderzobnin-zabbix-app# ./gpx_zabbix-plugin_linux_amd64 
> {"@level":"debug","@message":"Profiler","@timestamp":"2023-08-29T09:24:50.970009-04:00","enabled":false}
> {"@level":"debug","@message":"Starting Zabbix datasource","@timestamp":"2023-08-29T09:24:50.970615-04:00"}
> {"@level":"debug","@message":"Serving plugin","@timestamp":"2023-08-29T09:24:50.971060-04:00","plugins":["resource","data","diagnostics"]}
> This binary is a plugin. These are not meant to be executed directly.
> Please execute the program that consumes these plugins, which will
> load any plugins automatically
```

_Try to run the plugin again..._

**Commands must be run with root permission.**

_Originally posted by @ThomasJPF in https://github.com/grafana/grafana-zabbix/issues/1604#issuecomment-1697422094_

**Comment by alexanderzobnin** [comment]
I'll keep it open for a while, but basically, there's a build issue. I need to rebuild a plugin without `glibc` dependency (which is by default enabled).

**Comment by aaujon** [comment]
Upgrading from Ubuntu 20.04 to 22.04 fixed this issue for me.

**Comment by alexanderzobnin** [comment]
I've released a new version that fixes an issue.

**Comment by jojomsk** [comment]
Alexander, greetings.
The problem is not solved.
At least on Win10 (I decided to test the plugin on this OS)
Grafana Version: 10.1.5
Plugin Version: 4.4.3
Zabbix Version: 5.0.3

Error text: logger=context userId=1 orgId=1 uname=admin t=2023-10-16T16:10:41.3062578+03:00 level=warn msg="Plugin unavailable" error="plugin unavailable" traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-10-16T16:10:41.3063929+03:00 level=error msg="Request Completed" method=POST path=/api/datasources/1/resources/ zabbix-api status=503 remote_addr=127.0.0.1 time_ms=16 duration=16.3011ms size=46 referer=http://localhost:3000/connections/datasources/edit/af144246-751b-49b4-a5da-825089ac368b/ handler=/ api/datasources/:id/resources/*

**Comment by zoltanbedi** [comment]
@jojomsk can you please open a separate issue with your problem?
